#apiVersion: v1
#kind: Namespace
#metadata:
#  name: tomcat-cluster
#  labels:
#    app: jsp-counter
#    server: tomcat
#---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: tomcat-cluster-sa
  namespace: tomcat-cluster
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tomcat-cluster-role
  namespace: tomcat-cluster
rules:
- apiGroups: [""]
  verbs: ["get", "list"]
  resources: ["pods"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tomcat-cluster-rolebinding
  namespace: tomcat-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tomcat-cluster-role
subjects:
- kind: ServiceAccount
  name: tomcat-cluster-sa
  namespace: tomcat-cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsp-counter-deployment
  namespace: tomcat-cluster
  labels:
    app: jsp-counter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jsp-counter
      server: tomcat
  template:
    metadata:
      labels:
        app: jsp-counter
        server: tomcat
    spec:
      serviceAccountName: tomcat-cluster-sa
      containers:
      - name: tomcat
        #image: image-registry.openshift-image-registry.svc:5000/hello-tekton/tomcat9-jsp-counter
        image: quay.io/azkaoru/tomcat9-jsp-counter
        imagePullPolicy: Always
        env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_LABELS
            value: "server=tomcat"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /jsp-counter/health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /jsp-counter/health
            port: 8080
          initialDelaySeconds: 60
---
kind: Service
apiVersion: v1
metadata:
  name: jsp-counter-service
  namespace: tomcat-cluster
spec:
  selector:
    app: jsp-counter
    server: tomcat
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Route
metadata:
  name: jsp-counter
  labels:
    app: jsp-counter
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: jsp-counter-service
